### ISSUE TITLE
Critical issue with certbot-0.31

### ISSUE THREAD

**Issue by NickJH** [eglooca/app-lets-encrypt#17]
There is a critical issue with certbot-0.31. If you create a certificate after updating to certbot-0.31, it will create a file /etc/letsencrypt/live/README. The webconfig then tries to look for certificates under /etc/letsencrypt/live/README such as /etc/letsencrypt/live/README/cert.pem as it is only expecting certificate folders in /etc/letsencrypt/live/, and then the webconfig gives an "Ooooops: Certificate not found."

A number of thoughts come to mind:
1 - the app could just trap the error and skip it
2 - the app could only search folders /etc/letsencrypt/live/ and not try to search regular files
3 - Dirty fix, but check of the existence of /etc/letsencrypt/live/README and delete it if it exists. This could even be put in the renew-hooks.

Note the README file does not appear to be created when a certificate is renewed with a line like:
`certbot certonly --standalone --max-log-backups 200 --preferred-challenges http-01 --preferred-challenges http-01 -d example.com`

So it seems to be on creation only.

**Comment by pcbaldwin** [comment]
That should be a straightforward fix.  

I'm a bit surprised that ClearOS 7.6 has not yet been released... that is months overdue!  Let's wait until ClearOS 7.6 is released with the major Certificate Manager update.  This app depends on those Certificate Manager changes (it's also a critical path for Openfire).

**Comment by marclaporte** [comment]
See also: https://github.com/WikiSuite/app-lets-encrypt/issues/18

**Comment by cc-daveloper** [comment]
[ClearOS 7.6 is released](https://www.clearos.com/resources/documentation/clearos/content:en_us:announcements_releases_clearos_7.6.0_community_release_information) and we have addressed this issue in [app-lets-encrypt 1.10.7](https://gitlab.com/clearos/vendors/wikisuite/app-lets-encrypt/issues/1). Fabio reported that there was an issue when he tried it but we've not be able to replicate any issues that he reported. We've not gotten any feedback from him so this is a 'bump' to see if there are lingering issues. Otherwise, we are ready to push this to the community.
